version: "3"

networks:
    common-network:
        driver: overlay

volumes:
    portainer_data:

services:

    # Docker Registry
    registry-srv:
      image: registry:2
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "0.5"
            memory: 124M
        restart_policy:
          condition: on-failure
      ports:
      - "5000:5000"
      networks:
      - common-network

    # Portainer UI
    portainer:
      image: portainer/portainer
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
      ports:
      - 9000:9000
      networks:
      - common-network
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

    #Spark Master
    spark-master:
      image: bde2020/spark-master:2.1.0-hadoop2.7
      ports:
        - "8080:8080"
        - "7077:7077"
        - "6066:6066"
      environment:
        - INIT_DAEMON_STEP=setup_spark
        - SPARK_MASTER_IP=0.0.0.0
      networks:
        - common-network

    #Spark Worker
    spark-worker:
      image: bde2020/spark-worker:2.1.0-hadoop2.7
      depends_on:
        - spark-master
      ports:
        - "8081:8081"
      environment:
        - "SPARK_MASTER=spark://spark-master:7077"
      networks:
        - common-network