version: "3"

networks:
    webnet:
        driver: overlay

services:
    registry-srv:
        # replace username/repo:tag with your name and image details
        image: registry:2
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.5"
                    memory: 124M
            restart_policy:
                condition: none
        ports:
            - "5000:5000"
        networks: 
            - webnet

    registry-web:
    # replace username/repo:tag with your name and image details
        image: hyper/docker-registry-web
        environment: 
            - REGISTRY_URL=http://registry-srv:5000/v2 
            - REGISTRY_NAME=localhost:5000
        depends_on: registry-srv
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.5"
                    memory: 124M
            restart_policy:
                condition: none
        depends_on: 
            - registry-srv
        ports:
            - "8080:8080"
        networks:
            - webnet