version: '3'

networks:
  spark-network:
    driver: overlay

services:
  spark-master:
    image: bde2020/spark-master:2.1.0-hadoop2.7
    ports:
      - "8080:8080"
      - "7077:7077"
      - "6066:6066"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - SPARK_MASTER_IP=0.0.0.0
    networks:
      - spark-network

  spark-worker:
    image: bde2020/spark-worker:2.1.0-hadoop2.7
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - spark-network