version: '3'

services:
  spark-master:
    image: fsoppelsa/spark-master
    environment:
        - SPARK_MASTER_IP=0.0.0.0
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - 8080:8080
      - 7077:7077
      - 6066:6066
    networks:
      - spark

  spark-worker:
    image: fsoppelsa/spark-worker
    environment:
        - SPARK_MASTER_IP=spark-master
    depends_on: 
    - spark-master
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - spark

networks:
  spark:
    driver: overlay